#!/bin/bash

IFS="`printf "\n\t"`"
set -eu

if [[ "$#" -lt 1 ]]; then
    echo "usage: $0 PACKAGE_NAME ..."
    exit 1
fi

pip2tgz="$(dirname "$0")/pip2tgz"
pkg2dijkstra="$(dirname "$0")/pkg2dijkstra"

tempdir="/tmp/_pip2dijkstra_temp/"
mkdir "$tempdir" 2>&1 > /dev/null

$pip2tgz "$tempdir" "$@"
files=($tempdir/*)
$pkg2dijkstra "${files[@]}"
rm -r "$tempdir"
