{
  "formatVersion": "1.1",
  "component": {
    "group": "io.spring.gradle",
    "module": "dependency-management-plugin",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "dependency-management-plugin-1.1.3.jar",
          "url": "dependency-management-plugin-1.1.3.jar",
          "sha1": "3209385654a7e661d68de95a5ea8fc11d8ce015e",
          "md5": "abc123"
        }
      ]
    }
  ]
}
