what:
  - copyrights
  - holders
  - holders_tallies
copyrights:
  - Copyright (c) 1996-2010 Julian Seward <jseward@bzip.org>
holders:
  - Julian Seward
holders_tallies:
  - value: Julian Seward
    count: 1
