#
# Copyright (c) 2017 nexB Inc. and others. All rights reserved.
# http://nexb.com and https://github.com/nexB/scancode-toolkit/
# The ScanCode software is licensed under the Apache License version 2.0.
# Data generated with ScanCode require an acknowledgment.
# ScanCode is a trademark of nexB Inc.
#
# You may not use this software except in compliance with the License.
# You may obtain a copy of the License at: http://apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.
#
# When you publish or redistribute any data created with ScanCode or any ScanCode
# derivative work, you must accompany this data with the following acknowledgment:
#
#  Generated with ScanCode and provided on an "AS IS" BASIS, WITHOUT WARRANTIES
#  OR CONDITIONS OF ANY KIND, either express or implied. No content created from
#  ScanCode should be considered or used as legal advice. Consult an Attorney
#  for any legal advice.
#  ScanCode is a free software code scanning tool from nexB Inc. and others.
#  Visit https://github.com/nexB/scancode-toolkit/ for support and download.

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

from itertools import islice

import typecode.contenttype
import commoncode.text

generated_keywords = (
    'generated by',
    'auto-generated',
    'automatically generated',
    # Apache Axis
    'auto-generated from WSDL',
    # jni javahl and others
    'do not edit this file',
    # jni javahl
    'it is machine generated',
    'by hibernate tools',
    'generated from idl',
    # castor generated files
    'following schema fragment specifies the',
    # Tomcat JSPC
    'automatically created by',
    # in GNU Classpath
    'This file was automatically generated by gnu.localegen from CLDR',
    'This document is automatically generated by gnu.supplementgen',
    # linux kernel/u-boot
    'This was automagically generated from',

    # Angular
    'THIS CODE IS GENERATED',
    'THIS CODE IS GENERATED - DO NOT MODIFY',

    # cython
    'Generated by Cython',
    # sqlite amalgamation
    'This file is an amalgamation of many separate C source files from SQLite',

    # various generated or last generated:
    'Generated on ',
    'Last Generated on ',

    # in freepascal unicode
    "This is an automatically created file",

    # generated by Postgres ECPG sql to c preprocessor
    'Processed by ecpg (regression mode)',
    'These include files are added by the preprocessor',

    'This README is generated, please do not update',

    'This file was automatically generated by genny.',
    'Any changes will be lost if this file is regenerated.',
)

max_lines = 150


def generated_code(location):
    """
    Return a line of extracted text from a file if that file is likely
    generated source code.

    for each of the the first few lines of a source code file
      if generated keywords are found in the line as lowercase
         yield the line text as a 'potentially_ generated' annotation
    """
    T = typecode.contenttype.get_type(location)
    if not T.is_text:
        return
    with open(location, 'rb') as filein:
        for line in islice(filein, max_lines):
            text = commoncode.text.toascii(line.strip())
            textl = text.lower()
            if any(kw in textl for kw in generated_keywords):
                # yield only the first 100 chars..
                yield text[:100]
