blank_issues_enabled: true
contact_links:
  - name: Gitter Chat
    url: https://gitter.im/aboutcode-org/discuss
    about: Please ask questions here.
  - name: Code Of Conduct
    url: https://github.com/nexB/scancode-toolkit/blob/develop/CODE_OF_CONDUCT.rst
    about: This space is protected by our Code Of Conduct. 