.\" IP indented paragraph
.\" TP hanging label
.\" 
.\" Copyright (c) 1993-2003 Paul Mackerras <paulus@samba.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THIS SOFTWARE IS PROVIDED "AS IS" AND THE AUTHORS DISCLAIM ALL WARRANTIES
and
Brad Parker.

.SH COPYRIGHT
Pppd is copyrighted and made available under conditions which provide
that it may be copied and used in source or binary forms provided that
the conditions listed below are met.  Portions of pppd are covered by
the following copyright notices:
.LP
Copyright (c) 1984-2000 Carnegie Mellon University. All rights
reserved.
.br
Copyright (c) 1993-2004 Paul Mackerras. All rights reserved.
.br
Copyright (c) 1995 Pedro Roque Marques.  All rights reserved.
.br
Copyright (c) 1995 Eric Rosenquist.  All rights reserved.
.br
Copyright (c) 1999 Tommi Komulainen.  All rights reserved.
.br
Copyright (C) Andrew Tridgell 1999
.br
Copyright (c) 2000 by Sun Microsystems, Inc.  All rights reserved.
.br
Copyright (c) 2001 by Sun Microsystems, Inc.  All rights reserved.
.br
Copyright (c) 2002 The Android Open Source Project
.LP
The copyright notices contain the following statements.
.LP
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:
.LP
1. Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
.LP
2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in
   the documentation and/or other materials provided with the