#   Created:    Tuesday, July 02, 2002
#
#   MPW Makefile for building expat under the "classic" (i.e. pre-X) Mac OS
#   Copyright © 2002 Daryle Walker
#   Portions Copyright © 2002 Thomas Wegner
#   See the COPYING file for distribution information
#