Document: scancode-toolkit
Title: Debian scancode-toolkit Manual
Author: <insert document author here>
Abstract: This manual describes what scancode-toolkit is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/scancode-toolkit/scancode-toolkit.sgml.gz

Format: postscript
Files: /usr/share/doc/scancode-toolkit/scancode-toolkit.ps.gz

Format: text
Files: /usr/share/doc/scancode-toolkit/scancode-toolkit.text.gz

Format: HTML
Index: /usr/share/doc/scancode-toolkit/html/index.html
Files: /usr/share/doc/scancode-toolkit/html/*.html
