# It is necessary if you want to build targets usually of interest
# only to the maintainer.

# Copyright (C) 2001, 2003 Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify