name: Test CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        run: |
          brew update
          brew install p7zip libarchive libmagic

      - name: Set up venv
        run: |
          python3 -m venv venv
          source venv/bin/activate
          cp setup-mini.cfg setup.cfg
          pip install -e .[system_provided,testing]

      - name: Run tests
        run: venv/bin/pytest -n 3 -vvs .
